improved error handling

diff --git a/src/lib/git b/src/lib/git
--- a/src/lib/git
+++ b/src/lib/git
@@ -7,39 +7,31 @@ git_check() {
         log ".git directory exists"
         return 0
     else
-        log ".git direcory does not exist."
-        return 1
+        abort ".git directory does not exist."
     fi
 }
 
 git_init() {
-    log "cd into zettelkasten"
-    cd "$ZETTEL_DATA" || exit 
-
-    if git_check; then
-       log "exists aborting"
-       exit 0
-    fi
-
     log "running git init"
-    git init
+    git init || abort "git init failed"
 }
 
 git_cmd() {
-    log "cd into zettelkasten"
-    cd "$ZETTEL_DATA" || exit 
-
+    git_check
     log "running git" "$@"
-    git "$@"
+    git "$@" || abort "Error running git $*"
 }
 
 git_publish() {
-   git_check || exit 0;
    git_cmd add -A
    timestamp=$(date -u +"%Y-%m-%d")
    git_cmd commit -m "publish $timestamp"
    git_cmd push
 }
+
+# stop here if file is being sourced, not run
+[[ "$0" != "$BASH_SOURCE" ]] && return
+cd "$ZETTEL_DATA" || abort "failed to cd to $ZETTEL_DATA"
 
 case "$1" in
     init)
diff --git a/src/lib/ref b/src/lib/ref
--- a/src/lib/ref
+++ b/src/lib/ref
@@ -3,26 +3,21 @@ set -e
 
 ref_insert() {
     eval "$(parse_args "$@")"
-    if grep -qx "$ref" "$ZETTEL_DATA/$zettel/$REFERENCE_FILENAME" ; then
-        log "reference already present"
-        exit
-    fi
+
+    [[ -d "$ZETTEL_DATA/$ref" ]] || abort "the zettel $ref does not exist."
+    grep -qx "$ref" "$ZETTEL_DATA/$zettel/$REFERENCE_FILENAME" && abort "Reference $ref already present."
 
     echo "$ref" >> "$ZETTEL_DATA/$zettel/$REFERENCE_FILENAME"
 }
 
 ref_ls() {
     eval "$(parse_args "$@")"
-    grep -v ^$ "$ZETTEL_DATA/$zettel/$REFERENCE_FILENAME" || log "error during ref ls"
+    grep -v ^$ "$ZETTEL_DATA/$zettel/$REFERENCE_FILENAME" || abort "failed getting refs"
 }
 
 ref_rm() {
     eval "$(parse_args "$@")"
-
-    if ! grep -qx "$ref" "$ZETTEL_DATA/$zettel/$REFERENCE_FILENAME" ; then
-        log "$ref not referenced by $zettel"
-        return 1
-    fi
+    grep -qx "$ref" "$ZETTEL_DATA/$zettel/$REFERENCE_FILENAME" || abort "No reference named $ref."
 
     updated="$(grep -vx "$ref" "$ZETTEL_DATA/$zettel/$REFERENCE_FILENAME")" || updated=""
     echo "$updated" > "$ZETTEL_DATA/$zettel/$REFERENCE_FILENAME"
@@ -30,9 +25,7 @@ ref_rm() {
 }
 
 # stop here if file is being sourced, not run
-if [ "$0" != "$BASH_SOURCE" ] ; then
-   return
-fi
+[[ "$0" != "$BASH_SOURCE" ]] && return
 
 case "$1" in
     insert)
diff --git a/src/lib/utils b/src/lib/utils
--- a/src/lib/utils
+++ b/src/lib/utils
@@ -6,48 +6,54 @@ log() {
 	echo "== $script_name $timestamp" "$@" >> "$LOG_FILE"
 }
 
+abort() {
+    log "Error: $1. Aborting."
+    echo "Error: $1. Aborting." >&2
+    exit 1
+}
+
 check_kasten() {
-    if ! [[ -d $ZETTEL_DATA ]]; then
-        echo "$ZETTEL_DATA does not exist. Please run init"
-        exit
-    fi
-    log "kasten directory: check passed"
+    [[ -d $ZETTEL_DATA ]] || abort "$ZETTEL_DATA does not exist. Please run init"
+    log "kasten check passed."
 }
 
 parse_args() {
+    # Initialize variables
+    zettel=""
+    new_zettel="" # This will get renamed in the future to new to be used for refs and tags as well
+    path=""
+    ref=""
+    tag=""
+    
     OPTSTRING=":z:p:n:r:t:"
 
     while getopts ${OPTSTRING} opt; do
-        #
-        # we never have spaces in zettels, tags or referneces
-        # to avoid bugs, so lets just remove them here
-        #
-        OPTARG=${OPTARG// /_}
         case ${opt} in
             z)
-                zettel=$OPTARG
+                zettel=${OPTARG// /_}
                 ;;
             n)
-                new_zettel=$OPTARG
+                new_zettel=${OPTARG// /_}
                 ;;
             p)
-                path=$OPTARG
+                path=${OPTARG}
                 ;;
             r)
-                ref=$OPTARG
+                ref=${OPTARG// /_}
                 ;;
             t)
-                tag=$OPTARG
+                tag=${OPTARG// /_}
                 ;;
             :)
-                log "missing args $OPTARG"; exit
+                log "Error: Missing argument for option -${OPTARG}"; exit 1
                 ;;
             ?)
-                log "invalid option: $OPTARG"; exit
+                log "Error: Invalid option -${OPTARG}"; exit 1
                 ;;
         esac
     done
 
+    # return variable assignments as string
     echo "zettel='$zettel';\
           new_zettel='$new_zettel';\
           path='$path';\
diff --git a/src/lib/zettel b/src/lib/zettel
--- a/src/lib/zettel
+++ b/src/lib/zettel
@@ -5,7 +5,7 @@ expand_template() (
     NAME="${1//_/ }"
     export NAME
     export PREAMBLE="$PREAMBLE_FILE"
-    envsubst < "$ZETTEL_TEMPLATE"
+    envsubst < "$ZETTEL_TEMPLATE" || abort "Failed to expand template"
 )
 
 copy_files() {
@@ -13,7 +13,7 @@ copy_files() {
     echo "copying..."
     
     # copy without copying permissions
-    cp --no-preserve=mode -r "$ETC_DIR/templates/kasten/." "$ZETTEL_DATA"
+    cp --no-preserve=mode -r "$ETC_DIR/templates/kasten/." "$ZETTEL_DATA" || abort "Failed to copy files"
 }
 
 zettel_init() {
@@ -23,13 +23,12 @@ zettel_init() {
         exit
     fi
     log "initializing new zettelkasten"
-    mkdir "$ZETTEL_DATA" || log "failed to init"
+    mkdir "$ZETTEL_DATA" || abort "Failed to initialize zettelkasten"
     copy_files
 }
 
-
 zettel_ls() {
-    list="$(find "$ZETTEL_DATA" -mindepth 2 -maxdepth 2 -type f -name "$ZETTEL_FILENAME")"
+    list="$(find "$ZETTEL_DATA" -mindepth 2 -maxdepth 2 -type f -name "$ZETTEL_FILENAME")" || abort "Failed to list zettels"
     for z in $list
     do
         # use faster regex to emulate $(basename $(dirname ...))
@@ -41,22 +40,22 @@ zettel_ls() {
 
 zettel_rm() {
     eval "$(parse_args "$@")"
-    rm -r "$ZETTEL_DATA/${zettel:?}" || log "error removing zettel"
+    rm -r "$ZETTEL_DATA/${zettel:?}" || abort "Error removing zettel: $zettel"
 }
 
 zettel_path() {
     eval "$(parse_args "$@")"
 
     if [[ -n $zettel ]]; then
-        [[ -d  "$ZETTEL_DATA/$zettel" ]] || exit 1
+        [[ -d  "$ZETTEL_DATA/$zettel" ]] || abort "Zettel directory does not exist: $zettel"
         echo "$ZETTEL_DATA/$zettel"
         exit
     elif [[ -n $path ]]; then 
         supplied="$(dirname "$(dirname "$path")")"
 
         # test validity of path
-        [[ "$ZETTEL_DATA" -ef "$supplied" ]] || exit 1
-        [[ -f $path ]] || exit 1
+        [[ "$ZETTEL_DATA" -ef "$supplied" ]] || abort "Invalid supplied path"
+        [[ -f $path ]] || abort "Path does not exist: $path"
         
         basename "$(dirname "$path")"
         exit
@@ -67,16 +66,12 @@ zettel_path() {
 zettel_insert() {
     eval "$(parse_args "$@")"
 
-    if [ -d "$ZETTEL_DATA/$zettel" ]; then
-        log "$zettel exists, aborting"
-        echo "$zettel"
-        exit 1
-    fi
+    [[ -d "$ZETTEL_DATA/$zettel" ]] && abort "$zettel already exists, aborting"
 
-    mkdir "$ZETTEL_DATA/$zettel" || exit
-    expand_template "$zettel" > "$ZETTEL_DATA/$zettel/$ZETTEL_FILENAME"
-    touch "$ZETTEL_DATA/$zettel/$REFERENCE_FILENAME" || exit
-    touch "$ZETTEL_DATA/$zettel/$TAG_FILENAME" || exit
+    mkdir "$ZETTEL_DATA/$zettel" || abort "Failed to create zettel directory: $zettel"
+    expand_template "$zettel" > "$ZETTEL_DATA/$zettel/$ZETTEL_FILENAME" || abort "Failed to create zettel file: $zettel"
+    touch "$ZETTEL_DATA/$zettel/$REFERENCE_FILENAME" || abort "Failed to create reference file: $zettel"
+    touch "$ZETTEL_DATA/$zettel/$TAG_FILENAME" || abort "Failed to create tag file: $zettel"
     log "created $zettel"
     echo "$zettel"
 }
@@ -87,18 +82,21 @@ zettel_mv() {
     new_title=$new_zettel
 
     log "moving zettel"
-    mv "$ZETTEL_DATA/$old_title" "$ZETTEL_DATA/$new_title" || exit
+    mv "$ZETTEL_DATA/$old_title" "$ZETTEL_DATA/$new_title" || abort "Failed to move zettel from $old_title to $new_title"
 
     log "updating references"
     for zet in $(zettel_ls); do
-        # if removal of ref was succesfull, update it
+        # if removal of ref was successful, update it
         if ref_rm -z "$zet" -r "$old_title" &> /dev/null; then
             log "-- updating reference of $zet"
-            ref_insert "-z" "$zet" "-r" "$new_title"
+            ref_insert "-z" "$zet" "-r" "$new_title" || abort "Failed to update reference for $zet"
         fi
     done
     echo "$new_title"
 }
+
+# stop here if file is being sourced, not run
+[[ "$0" != "$BASH_SOURCE" ]] && return
 
 case "$1" in
     init)
@@ -128,6 +126,6 @@ case "$1" in
         zettel_insert "$@"
         ;;
     *)
-        echo "invalid top level command $1."
+        abort "Invalid top-level command: $1"
         ;;
 esac
